### ISSUE TITLE
Can the Cisco CiscoDPneighbor.tpl be updated so that the Neighbor address isn't in Hex

### ISSUE THREAD

**Issue by byronmorales** [extremenetworks/XMC-Report-Views#3]
It would be nicer to see the "Neighbor Address" as an IP instead of hex.

**Comment by ZdenekPala** [comment]
Hi.

I fully agree with you. Unfortunately, the Flexview can't do so such a complex transformation of the response. If the device does report it in the human-readable format then the Flexview will display it.

Sorry for not having a better answer for you.

**Comment by byronmorales** [comment]
I was hoping that an expression could be used to modify the value. But I wasn't  familiar with the syntax to pull it off. Or that there was a built in function like long2ip in php that I was missing.

Thanks for getting back to me though.
